server:
  port: 8080
  servlet:
    context-path: /EstateAnalysis
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.50/EstateAnalysis?characterEncoding=utf-8&useSSL=false
